In [16]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [17]:
df = pd.read_csv("2016-2022.csv", index_col="data_id")
df.head()

,iso,event_id_cnty,event_id_no_cnty,event_date,year,time_precision,event_type,sub_event_type,actor1,assoc_actor_1,inter1,actor2,assoc_actor_2,inter2,interaction,region,country,admin1,admin2,admin3,location,latitude,longitude,geo_precision,source,source_scale,notes,fatalities,timestamp,iso3
data_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
8912977,356,IND107923,107923.0,18 March 2022,2022,1,Riots,Mob violence,Rioters (India),Singraur Caste Group (India); Rajput Caste Gro...,5,Rioters (India),Sonkar Caste Group (India); Dalit Caste Group ...,5,55,South Asia,India,Uttar Pradesh,Fatehpur,Khaga,Kishanpur,25.6422,81.0244,1,Amar Ujala,Subnational,"On 18 March 2022, members of two caste groups ...",0,1647961433,IND
8912990,356,IND107846,107846.0,18 March 2022,2022,1,Protests,Peaceful protest,Protesters (India),Labour Group (India),6,NaN,NaN,0,60,South Asia,India,Maharashtra,Mumbai City,Mumbai City,Mumbai - Azad Maidan,18.9388,72.8321,1,Asian News International,National,"On 18 March 2022, aircraft technicians, employ...",0,1647961433,IND
8913012,356,IND107941,107941.0,18 March 2022,2022,1,Protests,Peaceful protest,Protesters (India),NaN,6,NaN,NaN,0,60,South Asia,India,Punjab,Sangrur,Malerkotla,Ahmedgarh,30.6785,75.8272,1,Chandigarh Tribune,National,"On 18 March 2022, activists of various organis...",0,1647961433,IND
8913089,356,IND107842,107842.0,18 March 2022,2022,1,Protests,Peaceful protest,Protesters (India),Health Workers (India),6,NaN,NaN,0,60,South Asia,India,Madhya Pradesh,Indore,Indore,Indore,22.7179,75.8333,1,Free Press Journal (India),National,"On 18 March 2022, doctors staged a protest at ...",0,1647961433,IND
8913091,356,IND107850,107850.0,18 March 2022,2022,1,Riots,Mob violence,Rioters (India),Government of India (2014-),5,Civilians (India),Former Government of India (2014-),7,57,South Asia,India,Madhya Pradesh,Bhind,Bhind,Kanavar,26.5622,78.9797,1,Free Press Journal (India),National,"On 18 March 2022, around half a dozen persons,...",1,1647961433,IND

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 107690 entries, 8912977 to 8543376
Data columns (total 30 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   iso               107690 non-null  int64
 1   event_id_cnty     107690 non-null  object
 2   event_id_no_cnty  107690 non-null  float64
 3   event_date        107690 non-null  object
 4   year              107690 non-null  int64
 5   time_precision    107690 non-null  int64
 6   event_type        107690 non-null  object
 7   sub_event_type    107690 non-null  object
 8   actor1            107690 non-null  object
 9   assoc_actor_1     76917 non-null   object
 10  inter1            107690 non-null  int64
 11  actor2            31375 non-null   object
 12  assoc_actor_2     11511 non-null   object
 13  inter2            107690 non-null  int64
 14  interaction       107690 non-null  int64
 15  region            107690 non-null  object
 16  country           107690 non-null  object
 17  admin1            107690 non-null  object
 18  admin2            107672 non-null  object
 19  admin3            105451 non-null  object
 20  location          107690 non-null  object
 21  latitude          107690 non-null  float64
 22  longitude         107690 non-null  float64
 23  geo_precision     107690 non-null  int64
 24  source            107690 non-null  object
 25  source_scale      107690 non-null  object
 26  notes             107690 non-null  object
 27  fatalities        107690 non-null  int64
 28  timestamp         107690 non-null  int64
 29  iso3              107690 non-null  object
dtypes: float64(3), int64(9), object(18)
memory usage: 25.5+ MB

In [19]:
len(df)

107690

In [20]:
#remove actor2 and assoc_actor_2
#consider using these columns as well (relation between actor 1 and actor 2)
df.drop(columns=["actor2", "assoc_actor_2"], inplace=True)

#fill null values on assoc_actor_1, admin2, admin3
df.fillna('Unknown', inplace=True)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 107690 entries, 8912977 to 8543376
Data columns (total 28 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   iso               107690 non-null  int64
 1   event_id_cnty     107690 non-null  object
 2   event_id_no_cnty  107690 non-null  float64
 3   event_date        107690 non-null  object
 4   year              107690 non-null  int64
 5   time_precision    107690 non-null  int64
 6   event_type        107690 non-null  object
 7   sub_event_type    107690 non-null  object
 8   actor1            107690 non-null  object
 9   assoc_actor_1     107690 non-null  object
 10  inter1            107690 non-null  int64
 11  inter2            107690 non-null  int64
 12  interaction       107690 non-null  int64
 13  region            107690 non-null  object
 14  country           107690 non-null  object
 15  admin1            107690 non-null  object
 16  admin2            107690 non-null  object
 17  admin3            107690 non-null  object
 18  location          107690 non-null  object
 19  latitude          107690 non-null  float64
 20  longitude         107690 non-null  float64
 21  geo_precision     107690 non-null  int64
 22  source            107690 non-null  object
 23  source_scale      107690 non-null  object
 24  notes             107690 non-null  object
 25  fatalities        107690 non-null  int64
 26  timestamp         107690 non-null  int64
 27  iso3              107690 non-null  object
dtypes: float64(3), int64(9), object(16)
memory usage: 23.8+ MB

In [22]:
df.head()

,iso,event_id_cnty,event_id_no_cnty,event_date,year,time_precision,event_type,sub_event_type,actor1,assoc_actor_1,inter1,inter2,interaction,region,country,admin1,admin2,admin3,location,latitude,longitude,geo_precision,source,source_scale,notes,fatalities,timestamp,iso3
data_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,
8912977,356,IND107923,107923.0,18 March 2022,2022,1,Riots,Mob violence,Rioters (India),Singraur Caste Group (India); Rajput Caste Gro...,5,5,55,South Asia,India,Uttar Pradesh,Fatehpur,Khaga,Kishanpur,25.6422,81.0244,1,Amar Ujala,Subnational,"On 18 March 2022, members of two caste groups ...",0,1647961433,IND
8912990,356,IND107846,107846.0,18 March 2022,2022,1,Protests,Peaceful protest,Protesters (India),Labour Group (India),6,0,60,South Asia,India,Maharashtra,Mumbai City,Mumbai City,Mumbai - Azad Maidan,18.9388,72.8321,1,Asian News International,National,"On 18 March 2022, aircraft technicians, employ...",0,1647961433,IND
8913012,356,IND107941,107941.0,18 March 2022,2022,1,Protests,Peaceful protest,Protesters (India),Unknown,6,0,60,South Asia,India,Punjab,Sangrur,Malerkotla,Ahmedgarh,30.6785,75.8272,1,Chandigarh Tribune,National,"On 18 March 2022, activists of various organis...",0,1647961433,IND
8913089,356,IND107842,107842.0,18 March 2022,2022,1,Protests,Peaceful protest,Protesters (India),Health Workers (India),6,0,60,South Asia,India,Madhya Pradesh,Indore,Indore,Indore,22.7179,75.8333,1,Free Press Journal (India),National,"On 18 March 2022, doctors staged a protest at ...",0,1647961433,IND
8913091,356,IND107850,107850.0,18 March 2022,2022,1,Riots,Mob violence,Rioters (India),Government of India (2014-),5,7,57,South Asia,India,Madhya Pradesh,Bhind,Bhind,Kanavar,26.5622,78.9797,1,Free Press Journal (India),National,"On 18 March 2022, around half a dozen persons,...",1,1647961433,IND